package com.epam.gmail.properties;

public enum Account {
	URL,GENERALSETTINGSURL,USERNAME01,USERNAME02,USERNAME03,USERPASSWORD01,USERPASSWORD02,USERPASSWORD03,
	USEREMAIL01,USEREMAIL02,USEREMAIL03;
}
